tweaks = {}

[general]
	"Enable 'q' Button" = true
	"'q' Button on the Right" = false
	"Use Anti Overlap" = true
	#Quark replaces the Piston logic to allow for its piston features to work. If you're having troubles, try turning this off.
	"Use Piston Logic Replacement" = true
	#Allowed values: (0,)
	"Piston Push Limit" = 12
	#Allowed values: (0,)
	"Advancement Visibility Depth" = 2
	#Blocks that Quark should treat as Shulker Boxes.
	"Shulker Boxes" = ["minecraft:white_shulker_box", "minecraft:orange_shulker_box", "minecraft:magenta_shulker_box", "minecraft:light_blue_shulker_box", "minecraft:yellow_shulker_box", "minecraft:lime_shulker_box", "minecraft:pink_shulker_box", "minecraft:gray_shulker_box", "minecraft:light_gray_shulker_box", "minecraft:cyan_shulker_box", "minecraft:purple_shulker_box", "minecraft:blue_shulker_box", "minecraft:brown_shulker_box", "minecraft:green_shulker_box", "minecraft:red_shulker_box", "minecraft:black_shulker_box"]
	#Should Quark treat anything with 'shulker_box' in its item identifier as a shulker box?
	"Interpret Shulker Box Like Blocks" = true
	#Set to true to enable a system that debugs quark's worldgen features. This should ONLY be used if you're asked to by a dev.
	"Enable Worldgen Watchdog" = false
	#Set to true if you need to find the class name for a screen that's causing problems
	"Print Screen Classnames" = false
	#A list of screens that don't play well with quark's buttons. Use "Print Screen Classnames" to find the names of any others you'd want to add.
	"Ignored Screens" = []
	#Set to true to make the quark big worldgen features such as stone clusters or underground biomes generate as spheres rather than unique shapes. It's faster, but won't look as cool
	"Use Fast Worldgen" = false
	#Enables quark network profiling features. Do not enable this unless requested to.
	"Enable Network Profiling" = false

[categories]
	Automation = true
	Building = true
	Management = true
	Tools = true
	Tweaks = true
	World = true
	Mobs = true
	Client = true
	Oddities = true
	Experimental = true

[automation]
	"Chain Linkage" = true
	"Chains Connect Blocks" = true
	Chute = true
	"Color Slime" = true
	"Dispensers Place Blocks" = true
	"Ender Watcher" = true
	"Endermites Form Shulkers" = true
	"Feeding Trough" = true
	Gravisand = true
	"Iron Rod" = true
	"Jukebox Automation" = true
	"Metal Buttons" = true
	"Obsidian Plate" = true
	"Pistons Move Tile Entities" = true
	"Redstone Circuit" = true
	"Weather Sensor" = true

	[automation.chain_linkage]
		#Can vehicle-linking chains be used for crafting chain armor?
		"Crafts Armor" = true

	[automation.color_slime]
		"Change Name" = true

	[automation.dispensers_place_blocks]
		Blacklist = ["minecraft:water", "minecraft:lava", "minecraft:fire"]

	[automation.endermites_form_shulkers]
		Chance = 0.005

	[automation.feeding_trough]
		#How long, in game ticks, between animals being able to eat from the trough
		#Allowed values: [1,)
		Cooldown = 30
		#The maximum amount of animals allowed around the trough's range for an animal to enter love mode
		"Max Animals" = 32
		#The chance (between 0 and 1) for an animal to enter love mode when eating from the trough
		#Allowed values: (0,1]
		"Love Chance" = 0.333333333
		Range = 10.0

	[automation.metal_buttons]
		"Enable Iron" = true
		"Enable Gold" = true

	[automation.pistons_move_tile_entities]
		"Enable Chests Moving Together" = true
		"Render Blacklist" = ["psi:programmer", "botania:starfield"]
		"Movement Blacklist" = ["minecraft:spawner", "integrateddynamics:cable", "randomthings:blockbreaker", "minecraft:ender_chest", "minecraft:enchanting_table", "minecraft:trapped_chest", "quark:spruce_trapped_chest", "quark:birch_trapped_chest", "quark:jungle_trapped_chest", "quark:acacia_trapped_chest", "quark:dark_oak_trapped_chest", "endergetic:bolloom_bud"]
		"Delayed Update List" = ["minecraft:dispenser", "minecraft:dropper"]

	[automation.redstone_circuit]
		"Enable Randomizer" = true
		"Enable Inductor" = true

[building]
	"Bamboo Mat" = true
	"Burn Vines" = true
	"Celebratory Lamps" = true
	"Cobblestone Bricks" = true
	"Compressed Blocks" = true
	"Duskbound Blocks" = true
	"Framed Glass" = true
	"Gold Bars" = true
	Grate = true
	Hedges = true
	"Iron Plates" = true
	"Item Frames" = true
	"Leaf Carpet" = true
	"Lit Lamp" = true
	Midori = true
	"More Brick Types" = true
	"More Potted Plants" = true
	"More Stone Variants" = true
	"Nether Brick Fence Gate" = true
	"Paper Decor" = true
	"Quilted Wool" = true
	Rope = true
	"Shallow Dirt" = true
	Shingles = true
	"Soul Sandstone" = true
	"Stained Planks" = true
	Stools = true
	"Sturdy Stone" = true
	"Tallow And Candles" = true
	Thatch = true
	"Tie Leads To Fences" = true
	Turf = true
	"Variant Bookshelves" = true
	"Variant Chests" = true
	"Variant Ladders" = true
	"Vertical Planks" = true
	"Vertical Slabs" = true
	"Wooden Posts" = true

	[building.celebratory_lamps]
		"Light Level" = 15

	[building.cobblestone_bricks]
		"Enable Blackstone Bricks" = true
		"Enable Dirt Bricks" = true
		"Enable Netherrack Bricks" = true
		"Enable Basalt Bricks" = true

	[building.compressed_blocks]
		"Charcoal Block and Blaze Lantern Stay On Fire Forever" = true
		#Allowed values: [0,)
		"Charcoal Block Fuel Time" = 16000
		#Allowed values: [0,)
		"Blaze Lantern Fuel Time" = 24000
		#Allowed values: [0,)
		"Stick Block Fuel Time" = 900
		#Allowed values: [0,)
		"Bamboo Bundle Fuel Time" = 500
		"Enable Charcoal Block" = true
		"Enable Sugar Cane Block" = true
		"Enable Bamboo Block" = true
		"Enable Cactus Block" = true
		"Enable Chorus Fruit Block" = true
		"Enable Stick Block" = true
		"Enable Apple Crate" = true
		"Enable Golden Apple Crate" = true
		"Enable Potato Crate" = true
		"Enable Carrot Crate" = true
		"Enable Beetroot Crate" = true
		"Enable Cocoa Bean Sack" = true
		"Enable Nether Wart Sack" = true
		"Enable Gunpowder Sack" = true
		"Enable Berry Sack" = true
		"Enable Blaze Lantern" = true
		"Enable Bonded Leather" = true
		"Enable Bonded Rabbit Hide" = true

	[building.gold_bars]
		"Generate In Nether Fortress" = true

	[building.item_frames]
		"Glass Item Frames Update Maps" = true

	[building.more_brick_types]
		"Enable Sandy Bricks" = true
		"Enable Snow Bricks" = true
		"Enable Magma Bricks" = true
		"Enable Charred Nether Bricks" = true
		"Enable Blackstone Variant Bricks" = true
		#This also comes with a utility recipe for Red Nether Bricks
		"Enable Blue Nether Bricks" = true
		#This also includes Red Sandstone Bricks and Soul Sandstone Bricks
		"Enable Sandstone Bricks" = true

	[building.more_stone_variants]
		"Enable Bricks" = true
		"Enable Chiseled Bricks" = true
		"Enable Pavement" = true
		"Enable Pillar" = true

	[building.rope]
		#Set to true to allow ropes to move Tile Entities even if Pistons Push TEs is disabled.
		#Note that ropes will still use the same blacklist.
		"Force Enable Move Tile Entities" = false
		"Enable Dispenser Behavior" = true

	[building.tallow_and_candles]
		"Candles Fall" = true
		#Allowed values: [0,)
		"Min Drop" = 1
		#Allowed values: [0,)
		"Max Drop" = 3
		#Allowed values: [0,)
		"Tallow Burn Time" = 200
		#Allowed values: [0,15]
		"Enchant Power" = 1.0

	[building.thatch]
		#Allowed values: [0,1]
		"Fall Damage Multiplier" = 0.5

	[building.variant_bookshelves]
		"Change Names" = true

	[building.variant_chests]
		"Replace Worldgen Chests" = true
		"Enable Reverting Wooden Chests" = true
		#Chests to put in each structure. The format per entry is "structure=chest", where "structure" is a structure ID, and "chest" is a block ID, which must correspond to a standard chest block.
		"Structure Chests" = ["minecraft:village_plains=quark:oak_chest", "minecraft:igloo=quark:spruce_chest", "minecraft:village_snowy=quark:spruce_chest", "minecraft:village_taiga=quark:spruce_chest", "minecraft:desert_pyramid=quark:birch_chest", "minecraft:jungle_pyramid=quark:jungle_chest", "minecraft:village_desert=quark:jungle_chest", "minecraft:village_savanna=quark:acacia_chest", "minecraft:mansion=quark:dark_oak_chest", "minecraft:pillager_outpost=quark:dark_oak_chest", "minecraft:ruined_portal=quark:crimson_chest", "minecraft:bastion_remnant=quark:crimson_chest", "minecraft:fortress=quark:nether_brick_chest", "minecraft:endcity=quark:purpur_chest"]

	[building.variant_ladders]
		"Change Names" = true
		"Enable Iron Ladder" = true

[management]
	"Chests In Boats" = true
	"Easy Transfering" = true
	"Hotbar Changer" = true
	"Inventory Sorting" = false
	"Item Sharing" = true
	"Right Click Armor" = true
	"Shulker Box Right Click" = true

	[management.easy_transfering]
		"Enable Shift Lock" = true

	[management.inventory_sorting]
		"Enable Player Inventory" = true
		"Enable Player Inventory In Chests" = true
		"Enable Chests" = true
		#Play a click when sorting inventories using keybindings
		"Satisfying Click" = true

	[management.item_sharing]
		"Render Items In Chat" = true

[tools]
	"Endermosh Music Disc" = true
	Abacus = true
	"Ambient Discs" = true
	"Ancient Tomes" = true
	"Bottled Cloud" = true
	Camera = true
	"Color Runes" = true
	"Pathfinder Maps" = true
	Pickarang = true
	"Seed Pouch" = true
	"Slime In A Bucket" = true
	Trowel = true

	[tools.endermosh_music_disc]
		"Play Endermosh During Enderdragon Fight" = false
		"Add To End City Loot" = true
		"Loot Weight" = 5
		"Loot Quality" = 1

	[tools.ambient_discs]
		"Drop On Spider Kill" = true

	[tools.ancient_tomes]
		#Set to 0 to not generate in Dungeons
		"Dungeon Weight" = 20
		#Set to 0 to not generate in Stronghold Libraries
		"Library Weight" = 30
		#Set to 0 to not generate in Bastions
		"Bastion Weight" = 25
		#Set to 0 to not generate in Woodland Mansions
		"Woodland Mansion Weight" = 15
		#Set to 0 to not generate in Nether Fortresses
		"Nether Fortress Weight" = 0
		#Set to 0 to not generate in Underwater Ruins
		"Underwater Ruin Weight" = 0
		#Set to 0 to not generate in Monster Boxes
		"Monster Box Weight" = 5
		"Item Quality" = 2
		"Normal Upgrade Cost" = 10
		"Limit Break Upgrade Cost" = 30
		"Valid Enchantments" = ["minecraft:feather_falling", "minecraft:thorns", "minecraft:sharpness", "minecraft:smite", "minecraft:bane_of_arthropods", "minecraft:knockback", "minecraft:fire_aspect", "minecraft:looting", "minecraft:sweeping", "minecraft:efficiency", "minecraft:unbreaking", "minecraft:fortune", "minecraft:power", "minecraft:punch", "minecraft:luck_of_the_sea", "minecraft:lure", "minecraft:loyalty", "minecraft:riptide", "minecraft:impaling", "minecraft:piercing"]

	[tools.bottled_cloud]
		"Cloud Level Bottom" = 127
		"Cloud Level Top" = 132

	[tools.color_runes]
		"Dungeon Weight" = 10
		"Nether Fortress Weight" = 8
		"Jungle Temple Weight" = 8
		"Desert Temple Weight" = 8
		"Item Quality" = 0
		"Apply Cost" = 5

	[tools.pathfinder_maps]
		#In this section you can add custom Pathfinder Maps. This works for both vanilla and modded biomes.
		#Each custom map must be on its own line.
		#The format for a custom map is as follows:
		#<id>,<level>,<min_price>,<max_price>,<color>,<name>
		#
		#With the following descriptions:
		# - <id> being the biome's ID NAME. You can find vanilla names here - https://minecraft.gamepedia.com/Biome#Biome_IDs
		# - <level> being the Cartographer villager level required for the map to be unlockable
		# - <min_price> being the cheapest (in Emeralds) the map can be
		# - <max_price> being the most expensive (in Emeralds) the map can be
		# - <color> being a hex color (without the #) for the map to display. You can generate one here - http://htmlcolorcodes.com/
		# - <name> being the display name of the map
		#
		#Here's an example of a map to locate Ice Mountains:
		#minecraft:ice_mountains,2,8,14,7FE4FF,Ice Mountains Pathfinder Map
		Customs = []
		"Search Radius" = 6400
		"Search Distance Increment" = 8
		"Xp From Trade" = 5

	[tools.pickarang]
		#How long it takes before the pickarang starts returning to the player if it doesn't hit anything.
		Timeout = 20
		#2 is Iron, 3 is Diamond.
		"Harvest Level" = 3
		#2 is Iron, 3 is Diamond.
		"Netherite Harvest Level" = 3
		#Set to -1 to have the Pickarang be unbreakable.
		Durability = 800
		#Set to -1 to have the Flamerang be unbreakable.
		"Netherite Durability" = 1040
		#22.5 is ender chests, 25.0 is monster boxes, 50 is obsidian. Most things are below 5.
		"Max Hardness" = 20.0
		#Set this to true to use the recipe without the Heart of Diamond, even if the Heart of Diamond is enabled.
		"Never Use Heart Of Diamond" = false
		#Set this to true to disable the short cooldown between throwing pickarangs.
		"No Cooldown" = false

	[tools.seed_pouch]
		"Max Items" = 640
		"Show All Variants In Creative" = true
		"Shift Range" = 3

	[tools.trowel]
		#Amount of blocks placed is this value + 1.
		#Set to 0 to make the Trowel unbreakable
		#Allowed values: [0,)
		"Trowel Max Durability" = 0

