onEvent('recipes', event => {
//修改木板合成配方
event.shapeless('minecraft:oak_planks',['notreepunching:flint_axe','minecraft:oak_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x minecraft:oak_planks',['notreepunching:iron_saw','minecraft:oak_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x minecraft:oak_planks',['notreepunching:iron_saw','minecraft:stripped_oak_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x minecraft:oak_planks'],['minecraft:oak_log'])
event.recipes.createCutting(['4x minecraft:oak_planks'],['minecraft:stripped_oak_log'])

event.shapeless('minecraft:birch_planks',['notreepunching:flint_axe','minecraft:birch_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x minecraft:birch_planks',['notreepunching:iron_saw','minecraft:birch_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x minecraft:birch_planks',['notreepunching:iron_saw','minecraft:stripped_birch_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x minecraft:birch_planks'],['minecraft:birch_log'])
event.recipes.createCutting(['4x minecraft:birch_planks'],['minecraft:stripped_birch_log'])

event.shapeless('minecraft:spruce_planks',['notreepunching:flint_axe','minecraft:spruce_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x minecraft:spruce_planks',['notreepunching:iron_saw','minecraft:spruce_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x minecraft:spruce_planks',['notreepunching:iron_saw','minecraft:stripped_spruce_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x minecraft:spruce_planks'],['minecraft:spruce_log'])
event.recipes.createCutting(['4x minecraft:spruce_planks'],['minecraft:stripped_spruce_log'])

event.shapeless('minecraft:jungle_planks',['notreepunching:flint_axe','minecraft:jungle_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x minecraft:jungle_planks',['notreepunching:iron_saw','minecraft:jungle_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x minecraft:jungle_planks',['notreepunching:iron_saw','minecraft:stripped_jungle_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x minecraft:jungle_planks'],['minecraft:jungle_log'])
event.recipes.createCutting(['4x minecraft:jungle_planks'],['minecraft:stripped_jungle_log'])

event.shapeless('minecraft:acacia_planks',['notreepunching:flint_axe','minecraft:acacia_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x minecraft:acacia_planks',['notreepunching:iron_saw','minecraft:acacia_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x minecraft:acacia_planks',['notreepunching:iron_saw','minecraft:stripped_acacia_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x minecraft:acacia_planks'],['minecraft:acacia_log'])
event.recipes.createCutting(['4x minecraft:acacia_planks'],['minecraft:stripped_acacia_log'])

event.shapeless('minecraft:dark_oak_planks',['notreepunching:flint_axe','minecraft:dark_oak_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x minecraft:dark_oak_planks',['notreepunching:iron_saw','minecraft:dark_oak_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x minecraft:dark_oak_planks',['notreepunching:iron_saw','minecraft:stripped_dark_oak_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x minecraft:dark_oak_planks'],['minecraft:dark_oak_log'])
event.recipes.createCutting(['4x minecraft:dark_oak_planks'],['minecraft:stripped_dark_oak_log'])

event.shapeless('minecraft:crimson_planks',['notreepunching:flint_axe','minecraft:crimson_stem']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x minecraft:crimson_planks',['notreepunching:iron_saw','minecraft:crimson_stem']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x minecraft:crimson_planks',['notreepunching:iron_saw','minecraft:stripped_crimson_stem']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x minecraft:crimson_planks'],['minecraft:crimson_stem'])
event.recipes.createCutting(['4x minecraft:crimson_planks'],['minecraft:stripped_crimson_stem'])

event.shapeless('minecraft:warped_planks',['notreepunching:flint_axe','minecraft:warped_stem']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x minecraft:warped_planks',['notreepunching:iron_saw','minecraft:warped_stem']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x minecraft:warped_planks',['notreepunching:iron_saw','minecraft:stripped_warped_stem']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x minecraft:warped_planks'],['minecraft:warped_stem'])
event.recipes.createCutting(['4x minecraft:warped_planks'],['minecraft:stripped_warped_stem'])

event.shapeless('biomesoplenty:palm_planks',['notreepunching:flint_axe','biomesoplenty:palm_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x biomesoplenty:palm_planks',['notreepunching:iron_saw','biomesoplenty:palm_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x biomesoplenty:palm_planks',['notreepunching:iron_saw','biomesoplenty:stripped_palm_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x biomesoplenty:palm_planks'],['biomesoplenty:palm_log'])
event.recipes.createCutting(['4x biomesoplenty:palm_planks'],['biomesoplenty:stripped_palm_log'])

event.shapeless('biomesoplenty:fir_planks',['notreepunching:flint_axe','biomesoplenty:fir_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x biomesoplenty:fir_planks',['notreepunching:iron_saw','biomesoplenty:fir_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x biomesoplenty:fir_planks',['notreepunching:iron_saw','biomesoplenty:stripped_fir_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x biomesoplenty:fir_planks'],['biomesoplenty:fir_log'])
event.recipes.createCutting(['4x biomesoplenty:fir_planks'],['biomesoplenty:stripped_fir_log'])

event.shapeless('biomesoplenty:redwood_planks',['notreepunching:flint_axe','biomesoplenty:redwood_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x biomesoplenty:redwood_planks',['notreepunching:iron_saw','biomesoplenty:redwood_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x biomesoplenty:redwood_planks',['notreepunching:iron_saw','biomesoplenty:stripped_redwood_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x biomesoplenty:redwood_planks'],['biomesoplenty:redwood_log'])
event.recipes.createCutting(['4x biomesoplenty:redwood_planks'],['biomesoplenty:stripped_redwood_log'])

event.shapeless('biomesoplenty:cherry_planks',['notreepunching:flint_axe','biomesoplenty:cherry_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x biomesoplenty:cherry_planks',['notreepunching:iron_saw','biomesoplenty:cherry_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x biomesoplenty:cherry_planks',['notreepunching:iron_saw','biomesoplenty:stripped_cherry_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x biomesoplenty:cherry_planks'],['biomesoplenty:cherry_log'])
event.recipes.createCutting(['4x biomesoplenty:cherry_planks'],['biomesoplenty:stripped_cherry_log'])

event.shapeless('biomesoplenty:mahogany_planks',['notreepunching:flint_axe','biomesoplenty:mahogany_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x biomesoplenty:mahogany_planks',['notreepunching:iron_saw','biomesoplenty:mahogany_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x biomesoplenty:mahogany_planks',['notreepunching:iron_saw','biomesoplenty:stripped_mahogany_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x biomesoplenty:mahogany_planks'],['biomesoplenty:mahogany_log'])
event.recipes.createCutting(['4x biomesoplenty:mahogany_planks'],['biomesoplenty:stripped_mahogany_log'])

event.shapeless('biomesoplenty:jacaranda_planks',['notreepunching:flint_axe','biomesoplenty:jacaranda_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x biomesoplenty:jacaranda_planks',['notreepunching:iron_saw','biomesoplenty:jacaranda_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x biomesoplenty:jacaranda_planks',['notreepunching:iron_saw','biomesoplenty:stripped_jacaranda_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x biomesoplenty:jacaranda_planks'],['biomesoplenty:jacaranda_log'])
event.recipes.createCutting(['4x biomesoplenty:jacaranda_planks'],['biomesoplenty:stripped_jacaranda_log'])

event.shapeless('biomesoplenty:willow_planks',['notreepunching:flint_axe','biomesoplenty:willow_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x biomesoplenty:willow_planks',['notreepunching:iron_saw','biomesoplenty:willow_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x biomesoplenty:willow_planks',['notreepunching:iron_saw','biomesoplenty:stripped_willow_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x biomesoplenty:willow_planks'],['biomesoplenty:willow_log'])
event.recipes.createCutting(['4x biomesoplenty:willow_planks'],['biomesoplenty:stripped_willow_log'])

event.shapeless('biomesoplenty:dead_planks',['notreepunching:flint_axe','biomesoplenty:dead_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x biomesoplenty:dead_planks',['notreepunching:iron_saw','biomesoplenty:dead_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x biomesoplenty:dead_planks',['notreepunching:iron_saw','biomesoplenty:stripped_dead_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x biomesoplenty:dead_planks'],['biomesoplenty:dead_log'])
event.recipes.createCutting(['4x biomesoplenty:dead_planks'],['biomesoplenty:stripped_dead_log'])

event.shapeless('biomesoplenty:magic_planks',['notreepunching:flint_axe','biomesoplenty:magic_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x biomesoplenty:magic_planks',['notreepunching:iron_saw','biomesoplenty:magic_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x biomesoplenty:magic_planks',['notreepunching:iron_saw','biomesoplenty:stripped_magic_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x biomesoplenty:magic_planks'],['biomesoplenty:magic_log'])
event.recipes.createCutting(['4x biomesoplenty:magic_planks'],['biomesoplenty:stripped_magic_log'])

event.shapeless('biomesoplenty:umbran_planks',['notreepunching:flint_axe','biomesoplenty:umbran_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x biomesoplenty:umbran_planks',['notreepunching:iron_saw','biomesoplenty:umbran_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x biomesoplenty:umbran_planks',['notreepunching:iron_saw','biomesoplenty:stripped_umbran_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x biomesoplenty:umbran_planks'],['biomesoplenty:umbran_log'])
event.recipes.createCutting(['4x biomesoplenty:umbran_planks'],['biomesoplenty:stripped_umbran_log'])

event.shapeless('biomesoplenty:hellbark_planks',['notreepunching:flint_axe','biomesoplenty:hellbark_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x biomesoplenty:hellbark_planks',['notreepunching:iron_saw','biomesoplenty:hellbark_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x biomesoplenty:hellbark_planks',['notreepunching:iron_saw','biomesoplenty:stripped_hellbark_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x biomesoplenty:hellbark_planks'],['biomesoplenty:hellbark_log'])
event.recipes.createCutting(['4x biomesoplenty:hellbark_planks'],['biomesoplenty:stripped_hellbark_log'])

event.shapeless('byg:aspen_planks',['notreepunching:flint_axe','byg:aspen_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:aspen_planks',['notreepunching:iron_saw','byg:aspen_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:aspen_planks',['notreepunching:iron_saw','byg:stripped_aspen_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:aspen_planks'],['byg:aspen_log'])
event.recipes.createCutting(['4x byg:aspen_planks'],['byg:stripped_aspen_log'])

event.shapeless('byg:baobab_planks',['notreepunching:flint_axe','byg:baobab_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:baobab_planks',['notreepunching:iron_saw','byg:baobab_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:baobab_planks',['notreepunching:iron_saw','byg:stripped_baobab_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:baobab_planks'],['byg:baobab_log'])
event.recipes.createCutting(['4x byg:baobab_planks'],['byg:stripped_baobab_log'])

event.shapeless('byg:blue_enchanted_planks',['notreepunching:flint_axe','byg:blue_enchanted_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:blue_enchanted_planks',['notreepunching:iron_saw','byg:blue_enchanted_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:blue_enchanted_planks',['notreepunching:iron_saw','byg:stripped_blue_enchanted_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:blue_enchanted_planks'],['byg:blue_enchanted_log'])
event.recipes.createCutting(['4x byg:blue_enchanted_planks'],['byg:stripped_blue_enchanted_log'])

event.shapeless('byg:bulbis_planks',['notreepunching:flint_axe','byg:bulbis_stem']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:bulbis_planks',['notreepunching:iron_saw','byg:bulbis_stem']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:bulbis_planks',['notreepunching:iron_saw','byg:stripped_bulbis_stem']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:bulbis_planks'],['byg:bulbis_stem'])
event.recipes.createCutting(['4x byg:bulbis_planks'],['byg:stripped_bulbis_stem'])

event.shapeless('byg:cherry_planks',['notreepunching:flint_axe','byg:cherry_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:cherry_planks',['notreepunching:iron_saw','byg:cherry_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:cherry_planks',['notreepunching:iron_saw','byg:stripped_cherry_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:cherry_planks'],['byg:cherry_log'])
event.recipes.createCutting(['4x byg:cherry_planks'],['byg:stripped_cherry_log'])

event.shapeless('byg:cika_planks',['notreepunching:flint_axe','byg:cika_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:cika_planks',['notreepunching:iron_saw','byg:cika_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:cika_planks',['notreepunching:iron_saw','byg:stripped_cika_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:cika_planks'],['byg:cika_log'])
event.recipes.createCutting(['4x byg:cika_planks'],['byg:stripped_cika_log'])

event.shapeless('byg:cypress_planks',['notreepunching:flint_axe','byg:cypress_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:cypress_planks',['notreepunching:iron_saw','byg:cypress_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:cypress_planks',['notreepunching:iron_saw','byg:stripped_cypress_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:cypress_planks'],['byg:cypress_log'])
event.recipes.createCutting(['4x byg:cypress_planks'],['byg:stripped_cypress_log'])

event.shapeless('byg:ebony_planks',['notreepunching:flint_axe','byg:ebony_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:ebony_planks',['notreepunching:iron_saw','byg:ebony_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:ebony_planks',['notreepunching:iron_saw','byg:stripped_ebony_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:ebony_planks'],['byg:ebony_log'])
event.recipes.createCutting(['4x byg:ebony_planks'],['byg:stripped_ebony_log'])

event.shapeless('byg:ether_planks',['notreepunching:flint_axe','byg:ether_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:ether_planks',['notreepunching:iron_saw','byg:ether_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:ether_planks',['notreepunching:iron_saw','byg:stripped_ether_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:ether_planks'],['byg:ether_log'])
event.recipes.createCutting(['4x byg:ether_planks'],['byg:stripped_ether_log'])

event.shapeless('byg:fir_planks',['notreepunching:flint_axe','byg:fir_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:fir_planks',['notreepunching:iron_saw','byg:fir_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:fir_planks',['notreepunching:iron_saw','byg:stripped_fir_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:fir_planks'],['byg:fir_log'])
event.recipes.createCutting(['4x byg:fir_planks'],['byg:stripped_fir_log'])

event.shapeless('byg:green_enchanted_planks',['notreepunching:flint_axe','byg:green_enchanted_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:green_enchanted_planks',['notreepunching:iron_saw','byg:green_enchanted_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:green_enchanted_planks',['notreepunching:iron_saw','byg:stripped_green_enchanted_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:green_enchanted_planks'],['byg:green_enchanted_log'])
event.recipes.createCutting(['4x byg:green_enchanted_planks'],['byg:stripped_green_enchanted_log'])

event.shapeless('byg:holly_planks',['notreepunching:flint_axe','byg:holly_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:holly_planks',['notreepunching:iron_saw','byg:holly_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:holly_planks',['notreepunching:iron_saw','byg:stripped_holly_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:holly_planks'],['byg:holly_log'])
event.recipes.createCutting(['4x byg:holly_planks'],['byg:stripped_holly_log'])

event.shapeless('byg:imparius_planks',['notreepunching:flint_axe','byg:imparius_stem']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:imparius_planks',['notreepunching:iron_saw','byg:imparius_stem']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:imparius_planks'],['byg:imparius_stem'])

event.shapeless('byg:jacaranda_planks',['notreepunching:flint_axe','byg:jacaranda_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:jacaranda_planks',['notreepunching:iron_saw','byg:jacaranda_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:jacaranda_planks',['notreepunching:iron_saw','byg:stripped_jacaranda_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:jacaranda_planks'],['byg:jacaranda_log'])
event.recipes.createCutting(['4x byg:jacaranda_planks'],['byg:stripped_jacaranda_log'])

event.shapeless('byg:lament_planks',['notreepunching:flint_axe','byg:lament_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:lament_planks',['notreepunching:iron_saw','byg:lament_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:lament_planks',['notreepunching:iron_saw','byg:stripped_lament_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:lament_planks'],['byg:lament_log'])
event.recipes.createCutting(['4x byg:lament_planks'],['byg:stripped_lament_log'])

event.shapeless('byg:mahogany_planks',['notreepunching:flint_axe','byg:mahogany_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:mahogany_planks',['notreepunching:iron_saw','byg:mahogany_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:mahogany_planks',['notreepunching:iron_saw','byg:stripped_mahogany_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:mahogany_planks'],['byg:mahogany_log'])
event.recipes.createCutting(['4x byg:mahogany_planks'],['byg:stripped_mahogany_log'])

event.shapeless('byg:mangrove_planks',['notreepunching:flint_axe','byg:mangrove_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:mangrove_planks',['notreepunching:iron_saw','byg:mangrove_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:mangrove_planks',['notreepunching:iron_saw','byg:stripped_mangrove_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:mangrove_planks'],['byg:mangrove_log'])
event.recipes.createCutting(['4x byg:mangrove_planks'],['byg:stripped_mangrove_log'])

event.shapeless('byg:maple_planks',['notreepunching:flint_axe','byg:maple_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:maple_planks',['notreepunching:iron_saw','byg:maple_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:maple_planks',['notreepunching:iron_saw','byg:stripped_maple_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:maple_planks'],['byg:maple_log'])
event.recipes.createCutting(['4x byg:maple_planks'],['byg:stripped_maple_log'])

event.shapeless('byg:nightshade_planks',['notreepunching:flint_axe','byg:nightshade_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:nightshade_planks',['notreepunching:iron_saw','byg:nightshade_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:nightshade_planks',['notreepunching:iron_saw','byg:imbued_nightshade_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:nightshade_planks',['notreepunching:iron_saw','byg:stripped_nightshade_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)    
event.recipes.createCutting(['4x byg:nightshade_planks'],['byg:nightshade_log'])
event.recipes.createCutting(['4x byg:nightshade_planks'],['byg:imbued_nightshade_log'])
event.recipes.createCutting(['4x byg:nightshade_planks'],['byg:stripped_nightshade_log'])

event.shapeless('byg:palm_planks',['notreepunching:flint_axe','byg:palm_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:palm_planks',['notreepunching:iron_saw','byg:palm_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:palm_planks',['notreepunching:iron_saw','byg:stripped_palm_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:palm_planks'],['byg:palm_log'])
event.recipes.createCutting(['4x byg:palm_planks'],['byg:stripped_palm_log'])

event.shapeless('byg:pine_planks',['notreepunching:flint_axe','byg:pine_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:pine_planks',['notreepunching:iron_saw','byg:pine_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:pine_planks',['notreepunching:iron_saw','byg:stripped_pine_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:pine_planks'],['byg:pine_log'])
event.recipes.createCutting(['4x byg:pine_planks'],['byg:stripped_pine_log'])

event.shapeless('byg:rainbow_eucalyptus_planks',['notreepunching:flint_axe','byg:rainbow_eucalyptus_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:rainbow_eucalyptus_planks',['notreepunching:iron_saw','byg:rainbow_eucalyptus_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:rainbow_eucalyptus_planks',['notreepunching:iron_saw','byg:stripped_rainbow_eucalyptus_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:rainbow_eucalyptus_planks'],['byg:rainbow_eucalyptus_log'])
event.recipes.createCutting(['4x byg:rainbow_eucalyptus_planks'],['byg:stripped_rainbow_eucalyptus_log'])

event.shapeless('byg:redwood_planks',['notreepunching:flint_axe','byg:redwood_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:redwood_planks',['notreepunching:iron_saw','byg:redwood_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:redwood_planks',['notreepunching:iron_saw','byg:stripped_redwood_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:redwood_planks'],['byg:redwood_log'])
event.recipes.createCutting(['4x byg:redwood_planks'],['byg:stripped_redwood_log'])

event.shapeless('byg:skyris_planks',['notreepunching:flint_axe','byg:skyris_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:skyris_planks',['notreepunching:iron_saw','byg:skyris_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:skyris_planks',['notreepunching:iron_saw','byg:stripped_skyris_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:skyris_planks'],['byg:skyris_log'])
event.recipes.createCutting(['4x byg:skyris_planks'],['byg:stripped_skyris_log'])

event.shapeless('byg:willow_planks',['notreepunching:flint_axe','byg:willow_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:willow_planks',['notreepunching:iron_saw','byg:willow_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:willow_planks',['notreepunching:iron_saw','byg:stripped_willow_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:willow_planks'],['byg:willow_log'])
event.recipes.createCutting(['4x byg:willow_planks'],['byg:stripped_willow_log'])

event.shapeless('byg:witch_hazel_planks',['notreepunching:flint_axe','byg:witch_hazel_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:witch_hazel_planks',['notreepunching:iron_saw','byg:witch_hazel_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:witch_hazel_planks',['notreepunching:iron_saw','byg:stripped_witch_hazel_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:witch_hazel_planks'],['byg:witch_hazel_log'])
event.recipes.createCutting(['4x byg:witch_hazel_planks'],['byg:stripped_witch_hazel_log'])

event.shapeless('byg:zelkova_planks',['notreepunching:flint_axe','byg:zelkova_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:zelkova_planks',['notreepunching:iron_saw','byg:zelkova_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:zelkova_planks',['notreepunching:iron_saw','byg:stripped_zelkova_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:zelkova_planks'],['byg:zelkova_log'])
event.recipes.createCutting(['4x byg:zelkova_planks'],['byg:stripped_zelkova_log'])

event.shapeless('byg:sythian_planks',['notreepunching:flint_axe','byg:sythian_stem']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:sythian_planks',['notreepunching:iron_saw','byg:sythian_stem']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:sythian_planks',['notreepunching:iron_saw','byg:stripped_sythian_stem']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:sythian_planks'],['byg:sythian_stem'])
event.recipes.createCutting(['4x byg:sythian_planks'],['byg:stripped_sythian_stem'])

event.shapeless('byg:embur_planks',['notreepunching:flint_axe','byg:embur_pedu']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x byg:embur_planks',['notreepunching:iron_saw','byg:embur_pedu']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x byg:embur_planks',['notreepunching:iron_saw','byg:stripped_embur_pedu']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x byg:embur_planks'],['byg:embur_pedu'])
event.recipes.createCutting(['4x byg:embur_planks'],['byg:stripped_embur_pedu'])

event.shapeless('atum:palm_planks',['notreepunching:flint_axe','atum:palm_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x atum:palm_planks',['notreepunching:iron_saw','atum:palm_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x atum:palm_planks',['notreepunching:iron_saw','atum:stripped_palm_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x atum:palm_planks'],['atum:palm_log'])
event.recipes.createCutting(['4x atum:palm_planks'],['atum:stripped_palm_log'])

event.shapeless('atum:deadwood_planks',['notreepunching:flint_axe','atum:deadwood_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x atum:deadwood_planks',['notreepunching:iron_saw','atum:deadwood_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x atum:deadwood_planks',['notreepunching:iron_saw','atum:stripped_deadwood_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x atum:deadwood_planks'],['atum:deadwood_log'])
event.recipes.createCutting(['4x atum:deadwood_planks'],['atum:stripped_deadwood_log'])

event.shapeless('betterendforge:mossy_glowshroom_planks',['notreepunching:flint_axe','betterendforge:mossy_glowshroom_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x betterendforge:mossy_glowshroom_planks',['notreepunching:iron_saw','betterendforge:mossy_glowshroom_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x betterendforge:mossy_glowshroom_planks',['notreepunching:iron_saw','betterendforge:mossy_glowshroom_stripped_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x betterendforge:mossy_glowshroom_planks'],['betterendforge:mossy_glowshroom_log'])
event.recipes.createCutting(['4x betterendforge:mossy_glowshroom_planks'],['betterendforge:mossy_glowshroom_stripped_log'])

event.shapeless('betterendforge:lacugrove_planks',['notreepunching:flint_axe','betterendforge:lacugrove_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x betterendforge:lacugrove_planks',['notreepunching:iron_saw','betterendforge:lacugrove_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x betterendforge:lacugrove_planks',['notreepunching:iron_saw','betterendforge:lacugrove_stripped_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x betterendforge:lacugrove_planks'],['betterendforge:lacugrove_log'])
event.recipes.createCutting(['4x betterendforge:lacugrove_planks'],['betterendforge:lacugrove_stripped_log'])

event.shapeless('betterendforge:end_lotus_planks',['notreepunching:flint_axe','betterendforge:end_lotus_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x betterendforge:end_lotus_planks',['notreepunching:iron_saw','betterendforge:end_lotus_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x betterendforge:end_lotus_planks',['notreepunching:iron_saw','betterendforge:end_lotus_stripped_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x betterendforge:end_lotus_planks'],['betterendforge:end_lotus_log'])
event.recipes.createCutting(['4x betterendforge:end_lotus_planks'],['betterendforge:end_lotus_stripped_log'])

event.shapeless('betterendforge:pythadendron_planks',['notreepunching:flint_axe','betterendforge:pythadendron_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x betterendforge:pythadendron_planks',['notreepunching:iron_saw','betterendforge:pythadendron_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x betterendforge:pythadendron_planks',['notreepunching:iron_saw','betterendforge:pythadendron_stripped_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x betterendforge:pythadendron_planks'],['betterendforge:pythadendron_log'])
event.recipes.createCutting(['4x betterendforge:pythadendron_planks'],['betterendforge:pythadendron_stripped_log'])

event.shapeless('betterendforge:dragon_tree_planks',['notreepunching:flint_axe','betterendforge:dragon_tree_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x betterendforge:dragon_tree_planks',['notreepunching:iron_saw','betterendforge:dragon_tree_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x betterendforge:dragon_tree_planks',['notreepunching:iron_saw','betterendforge:dragon_tree_stripped_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x betterendforge:dragon_tree_planks'],['betterendforge:dragon_tree_log'])
event.recipes.createCutting(['4x betterendforge:dragon_tree_planks'],['betterendforge:dragon_tree_stripped_log'])

event.shapeless('betterendforge:tenanea_planks',['notreepunching:flint_axe','betterendforge:tenanea_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x betterendforge:tenanea_planks',['notreepunching:iron_saw','betterendforge:tenanea_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x betterendforge:tenanea_planks',['notreepunching:iron_saw','betterendforge:tenanea_stripped_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x betterendforge:tenanea_planks'],['betterendforge:tenanea_log'])
event.recipes.createCutting(['4x betterendforge:tenanea_planks'],['betterendforge:tenanea_stripped_log'])

event.shapeless('betterendforge:helix_tree_planks',['notreepunching:flint_axe','betterendforge:helix_tree_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x betterendforge:helix_tree_planks',['notreepunching:iron_saw','betterendforge:helix_tree_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x betterendforge:helix_tree_planks',['notreepunching:iron_saw','betterendforge:helix_tree_stripped_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x betterendforge:helix_tree_planks'],['betterendforge:helix_tree_log'])
event.recipes.createCutting(['4x betterendforge:helix_tree_planks'],['betterendforge:helix_tree_stripped_log'])

event.shapeless('betterendforge:umbrella_tree_planks',['notreepunching:flint_axe','betterendforge:umbrella_tree_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x betterendforge:umbrella_tree_planks',['notreepunching:iron_saw','betterendforge:umbrella_tree_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x betterendforge:umbrella_tree_planks',['notreepunching:iron_saw','betterendforge:umbrella_tree_stripped_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x betterendforge:umbrella_tree_planks'],['betterendforge:umbrella_tree_log'])
event.recipes.createCutting(['4x betterendforge:umbrella_tree_planks'],['betterendforge:umbrella_tree_stripped_log'])

event.shapeless('betterendforge:jellyshroom_planks',['notreepunching:flint_axe','betterendforge:jellyshroom_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x betterendforge:jellyshroom_planks',['notreepunching:iron_saw','betterendforge:jellyshroom_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x betterendforge:jellyshroom_planks',['notreepunching:iron_saw','betterendforge:jellyshroom_stripped_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x betterendforge:jellyshroom_planks'],['betterendforge:jellyshroom_log'])
event.recipes.createCutting(['4x betterendforge:jellyshroom_planks'],['betterendforge:jellyshroom_stripped_log'])

event.shapeless('betterendforge:lucernia_planks',['notreepunching:flint_axe','betterendforge:lucernia_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x betterendforge:lucernia_planks',['notreepunching:iron_saw','betterendforge:lucernia_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x betterendforge:lucernia_planks',['notreepunching:iron_saw','betterendforge:lucernia_stripped_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x betterendforge:lucernia_planks'],['betterendforge:lucernia_log'])
event.recipes.createCutting(['4x betterendforge:lucernia_planks'],['betterendforge:lucernia_stripped_log'])

event.shapeless('terraincognita:apple_planks',['notreepunching:flint_axe','terraincognita:apple_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x terraincognita:apple_planks',['notreepunching:iron_saw','terraincognita:apple_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x terraincognita:apple_planks',['notreepunching:iron_saw','terraincognita:stripped_apple_wood']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x terraincognita:apple_planks'],['terraincognita:apple_log'])
event.recipes.createCutting(['4x terraincognita:apple_planks'],['terraincognita:stripped_apple_wood'])

event.shapeless('tconstruct:greenheart_planks',['notreepunching:flint_axe','tconstruct:greenheart_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x tconstruct:greenheart_planks',['notreepunching:iron_saw','tconstruct:greenheart_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x tconstruct:greenheart_planks',['notreepunching:iron_saw','tconstruct:stripped_greenheart_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x tconstruct:greenheart_planks'],['tconstruct:greenheart_log'])
event.recipes.createCutting(['4x tconstruct:greenheart_planks'],['tconstruct:stripped_greenheart_log'])

event.shapeless('tconstruct:skyroot_planks',['notreepunching:flint_axe','tconstruct:skyroot_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x tconstruct:skyroot_planks',['notreepunching:iron_saw','tconstruct:skyroot_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x tconstruct:skyroot_planks',['notreepunching:iron_saw','tconstruct:stripped_skyroot_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x tconstruct:skyroot_planks'],['tconstruct:skyroot_log'])
event.recipes.createCutting(['4x tconstruct:skyroot_planks'],['tconstruct:stripped_skyroot_log'])

event.shapeless('tconstruct:bloodshroom_planks',['notreepunching:flint_axe','tconstruct:bloodshroom_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x tconstruct:bloodshroom_planks',['notreepunching:iron_saw','tconstruct:bloodshroom_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x tconstruct:bloodshroom_planks',['notreepunching:iron_saw','tconstruct:stripped_bloodshroom_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x tconstruct:bloodshroom_planks'],['tconstruct:bloodshroom_log'])
event.recipes.createCutting(['4x tconstruct:bloodshroom_planks'],['tconstruct:stripped_bloodshroom_log'])

event.shaped('1x cataclysm:chorus_planks',[
    'cc ',
    'cc ',
    '   '
],{
    c:'minecraft:chorus_fruit'
})

event.shapeless('betterlands:juniper_planks',['notreepunching:flint_axe','betterlands:juniper_log']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x betterlands:juniper_planks',['notreepunching:iron_saw','betterlands:juniper_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.shapeless('2x betterlands:juniper_planks',['notreepunching:iron_saw','betterlands:stripped_juniper_log']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x betterlands:juniper_planks'],['betterlands:juniper_log'])
event.recipes.createCutting(['4x betterlands:juniper_planks'],['betterlands:stripped_juniper_log'])

event.shapeless('shroomed:shroomwood_planks',['notreepunching:flint_axe','shroomed:hard_mushroom_stem']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x shroomed:shroomwood_planks',['notreepunching:iron_saw','shroomed:hard_mushroom_stem']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x shroomed:shroomwood_planks'],['shroomed:hard_mushroom_stem'])

event.shapeless('shroomed:blue_hard_mushroom_stem',['notreepunching:flint_axe','shroomed:blue_hard_mushroom_stem']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x shroomed:blue_hard_mushroom_stem',['notreepunching:iron_saw','shroomed:blue_hard_mushroom_stem']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x shroomed:blue_hard_mushroom_stem'],['shroomed:blue_hard_mushroom_stem'])

event.shapeless('shroomed:orange_shroomwood_planks',['notreepunching:flint_axe','shroomed:orange_hard_mushroom_stem']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x shroomed:orange_shroomwood_planks',['notreepunching:iron_saw','shroomed:orange_hard_mushroom_stem']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x shroomed:orange_shroomwood_planks'],['shroomed:orange_hard_mushroom_stem'])

event.shapeless('shroomed:purple_shroomwood_planks',['notreepunching:flint_axe','shroomed:purple_hard_mushroom_stem']).damageIngredient(Item.of('notreepunching:flint_axe'),1)
event.shapeless('2x shroomed:purple_shroomwood_planks',['notreepunching:iron_saw','shroomed:purple_hard_mushroom_stem']).damageIngredient(Item.of('notreepunching:iron_saw'),1)
event.recipes.createCutting(['4x shroomed:purple_shroomwood_planks'],['shroomed:purple_hard_mushroom_stem'])
})